version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:80"
    networks:
      - proshop_network
    depends_on:
      - backend

  backen:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run server
    ports:
      - "5000:5000"
    env_file:
      - ./.env

    volumes:
      - ./backend:/usr/src/app
      - ./uploads:/app/uploads
    networks:
      - proshop_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "443:443"
      - "8080:80"
    volumes:
      - ./frontend/nginx.conf:etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/log/nginx:/var/log/nginx
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    networks:
      - proshop_network

  networks:
    proshop_network:
      driver: bridge
