name: Auto Deploy ProShop to AWS

on:
  push:
    branches:
      - main #Triggers deployment on push to the main branch
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PROSHOP_EC2_SSH }}

      - name: Add AWS Droplet to known hosts
        # Use the host secret here
        # ssh-keyscan ..aws-instance-ip >> ~/.ssh/known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.PROSHOP_EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to AWS Droplet
        run: |
          ssh ubuntu@35.183.5.83 << 'EOF'
            cd ~/e-commerce-shop
            sudo git pull origin main
            sudo docker-compose down
            sudo docker-compose up -d --build
          EOF
